version: "3.2"
services:
    frontend:
        image: tmp-app-frontend:latest
        ports:
            - 1338:80
        volumes:
            # You need to create this file locally yourself
            - ./runtime-env.js:/usr/share/nginx/html/runtime-env.js

    backend:
        image: tmp-app-backend:latest
        ports:
            - 1337:8080
        # volumes:
        #     - ./database.db:/app/database.db # TODO: fix it database is not created yet ehn creating container
        # environment:
        # ACCESS_TOKEN_SECRET: dasda
        # REFRESH_TOKEN_SECRET: asfsdfsd
